### ISSUE TITLE
Arquivo de entrada

### ISSUE THREAD

**Issue by guimadalozzo** [thypad/bovespa#5]
Olá.

Qual é o arquivo de entrada?

`import bovespa`
`bf = bovespa.File("???")`
`for rec in bf.query(stock='GRND3'):`
`    print('<{}, {}, {}>'.format(rec.date, rec.stock_symbol, rec.price_close))`

Ocorre um exception independente do arquivo que informo (TXT da BOVESPA, XLS ou CSV com histórico, TXT vazio).
`Exception: data length is not 245 bytes`

**Comment by thypad** [comment]
Oi guilherme, desculpa a demora em responder.
O Arquivo de entrada é o arquivo de histórico de cotações que a B3
disponibiliza no site deles.

Abs,
--
Thyago Neves Porpino

**Comment by fabiomathu** [comment]
Thyago, saudacoes, 
Gostei muito da proposta do trabalho, mas estou com esse probleminha semelhante,
tens algum endereco exemplo da B3, ou pode me indicar como eu consigo esse endereco?
pq entrei no site da B3 e precisa abrir uns arquivos zipados pra chegar nos arquivos
 desde ja obrigado

**Comment by anisiomqs** [comment]
Opa, @fabiomathu. Não sei se é o que você espera, mas vou contribuir com meus 50 centavos. Eu baixei os arquivos [daqui](http://www.bmfbovespa.com.br/en_us/services/market-data/historical-data/equities/historical-data/). A extração gera um arquivo com o mesmo nome, sem a extensão. Daí é só:

```
bf = bovespa.File("COTAHIST.A1990")
```

Imagino que seja difícil baixar esses arquivos automaticamente por que para cada um deles tem que informar um captcha.

**Comment by leandropons** [comment]
![image](https://user-images.githubusercontent.com/61729103/77971676-0a391800-733b-11ea-98ca-c4ac703d1e1c.png)


Fala brother, eu sou bem novo no assunto, poderia me dar um help, apesar do correto adrress ele me da este erro.
Ja ate troquei o file, mas continua o erro.

Vlew pela ajuda.

**Comment by thypad** [comment]
Esse erro ocorre porque o "\" representa uma flag de caracter especial, se
você quiser passar o path desse jeito você precisa
especificar que a string é raw:

r"C:\...\COTAHIST.txt"

ou usar / no path:

"C:/..../COTAHIST.txt"

**Comment by phspagiari** [comment]
Isso aqui aconteceu com vocês?

```
>>> bf = bovespa.File("COTAHIST_A2020.TXT")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'File'
```

**Comment by fernandofsilva** [comment]
@phspagiari testei e funcionou perfeitamente

```
import pandas as pd
import bovespa

row = list()

bf = bovespa.File('Options-Trading/datasets/COTAHIST_A2020.TXT')
for rec in bf.query():
    row.append(
        [rec.bdi_code, rec.board_lot, rec.company_name, rec.date,
         rec.especification, rec.info, rec.isin_code, rec.market,
         rec.parse_data, rec.price_close, rec.price_high, rec.price_low,
         rec.price_mean, rec.price_open, rec.quantity, rec.stock_code,
         rec.type, rec.volume]
    )

header = ['bdi_code', 'board_lot', 'company_name', 'date', 'especification',
          'info', 'isin_code', 'market', 'parse_data', 'price_close',
          'price_high', 'price_low', 'price_mean', 'price_open', 'quantity',
          'stock_code', 'type', 'volume']

example = pd.DataFrame(data=row, columns=header)
example.head()
```

Gostaria de saber se alguém conseguiu fazer o parser do arquivo utilizando os outros campos, tenho interesse nas informações sobre opções (vencimento, preço de exercício e etc)

**Comment by fabiomathu** [comment]
bf = bovespa.File('Options-Trading/datasets/COTAHIST_A2020.TXT')


ta dando pau aqui... o q acontece?


[image: image.png]

sou novato com o python

**Comment by fernandofsilva** [comment]
> bf = bovespa.File('Options-Trading/datasets/COTAHIST_A2020.TXT') ta dando pau aqui... o q acontece? [image: image.png] sou novato com o python
> […](#)

@fabiomathu não consigo ver a imagem que você anexou, porém pela linha que você referência com erro, o problema deve estar no caminho que você está especificando pro arquivo da Bovespa no seu computador.

```
bf = bovespa.File('<pasta com o arquivo>/<nome do arquivo>.TXT')
```

**Comment by fabiomathu** [comment]
certo... e os arquivos da bovespa eu pego aonde? to procurando aqui

**Comment by fernandofsilva** [comment]
> certo... e os arquivos da bovespa eu pego aonde? to procurando aqui
> […](#)

Você precisa ler o README do pacote, lá está explicando tudo e essa sessão do Github é pra tratamento de problemas, não é fórum de dúvidas, recomendo você olhar o [StackOverflow](http://stackoverflow.com), lá você consegue tirar todas as dúvidas de python, pacotes e etc.

**Comment by fabiomathu** [comment]
valeu!

**Comment by gustavo-silva98** [comment]
> Isso aqui aconteceu com vocês?
> 
> ```
> >>> bf = bovespa.File("COTAHIST_A2020.TXT")
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> AttributeError: 'module' object has no attribute 'File'
> ```

Aqui aconteceu o mesmo erro. Até agora não descobri como fazer funcionar.
